### PR TITLE
Switch to quarkus-l10n-utils, which comes with many improvements

### PR DESCRIPTION
**Pull request by ynojima**
This pull-request reorganizes scripts under `bin` directory to [quarkus-l10n-utils](https://github.com/doc-l10n-kit/quarkus-l10n-utils) repository, and placed it under `vendor` directory.

## What's changed?

- Switch to `quarkus-l10n-utils` 
  - To sync utility scripts across localization repositories(cn.quarkus.io, es.quarkus.io, pt.quarkus.io and ja.quarkus.io), a shared repository `quarkus-l10n-utils` is introduced, and it is placed within the `vendor` directory.
- Asciidoc localization is now implemented with a Jekyll plugin(https://github.com/doc-l10n-kit/jekyll-l10n) instead of `po4a::asciidoc`
  - Since `po4a::asciidoc` parser is not accurate, it sometimes failed to extract and localize sentences. With the new Jekyll plugin approach, original ruby asciidoc parser, which is used for Jekyll site build process, never fails to parse the asciidoc files. 
  - Moreover, the Jekyll localization plugin filters out unnecessary source code block contents from .po files. This reduces .po file size and translators can increase their productivity.
  - markdown, yaml and html files are still processed with po4a
- Some files are now processed in parallel to reduce the build time.
- DeepL Glossary support
  - The DeepL API now provides the ability to customize translation results by uploading glossaries.
  - We've added features for managing DeepL glossaries and the configured glossary is used for localization.

## Impact to translator workflow

No impact is expected. 
As before, sentences are automatically extracted from the original files to .po files, and .po files are automatically filled with translation memory or draft translation generated with DeepL API.
What translators need to do is review and correct the draft, and send a pull-request. GitHub Actions will automatically build a preview site.

## Known issue

Some sentences improperly parsed with `po4a::asciidoc` will be erased during the migration. 
Most of the sentences (hopefully more than 99%) will be kept without problem, but you need to translate the some erased sentences again.

### CODE REVIEW

**Comment by ynojima** [comment]
The site preview build doesn't work becasue build script is fetched from `master` branch, but .po files are from this pull-request branch. This mismatch breaks this build. 
Please checkout this branch in your local environment, and try following commands to preview:
```
vendor/quarkus-l10n-utils/bin/build
vendor/quarkus-l10n-utils/bin/exec-jekyll-serve
```

**Comment by ynojima** [comment]
Rebased

**Comment by gastaldi** [comment]
@ynojima Surge.sh is complaining that the uploaded site is too large to preview it. Can you incorporate the changes you did in https://github.com/quarkusio/quarkusio.github.io/pull/1826 here too?

**Comment by gastaldi** [comment]
I'll merge this PR and we can do that in a separate PR

**Comment by ynojima** [comment]
It seems the `upstream` submodule in `pt.quarkus.io` is not latest, and it doesn't contain the change of  https://github.com/quarkusio/quarkusio.github.io/pull/1826 now.

I triggered `sync-upstream` workflow now, and I think it will resolve this issue.

**Comment by ynojima** [comment]
Oh, it failed. 
https://github.com/quarkusio/pt.quarkus.io/actions/runs/6746952278/job/18342016524

The scripts presupposes the default branch is `main`. 
Is it possible to switch the default branch from `master` to `main`?

**Comment by gastaldi** [comment]
Of course. We'll just have to adjust the workflow scripts too. Want to send a PR?

**Comment by ynojima** [comment]
Yes, I sent a pull-request to update workflow definitions: https://github.com/quarkusio/pt.quarkus.io/pull/62

**Pull request merged**
